### ISSUE TITLE
ESP8266 not working

### ISSUE THREAD

**Issue by lucoceano** [parse-community/Parse-SDK-Arduino#10]
Hi, I'm trying to use Parse ina ESP8266-1 but it isn't working properly. I've tried to create, update, remove and get object from Parse but the response is always empty or doesn't work (for update, remove and create).

This is the code I'm trying on, any idea on why doesn't work?

``` cpp
  ParseObjectUpdate update;
  update.setClassName("Cube");
  update.setObjectId("obj-id");
  update.add("stringTest", "changing value");
  update.send();
```

Thanks!

**Comment by Pietroga** [comment]
I have the same Problem. With the old version I didn't have Problem, but now doesn't works.

**Comment by Tom-Fox1** [comment]
I’m closing this as this project has been retired due to lack of use & contribution, if you wish to continue to use it please fork it or if you wish to maintain this project make yourself known
