### ISSUE TITLE
Example how to connect ESP8266 to custom server

### ISSUE THREAD

**Issue by waqas-ogc** [parse-community/Parse-SDK-Arduino#12]
Is there any example on how to connect ESP8266 to custom server ?

**Comment by tabvn** [comment]
You need tweek a bit in this librarry 

/src/internal/esp8266/parseClient.cpp

const bool DEBUG = false;
const char* PARSE_API = "your-domain.com"; //"api.parse.com";
const char* USER_AGENT = "arduino-esp8266.v.1.0.1";
const char* CLIENT_VERSION = "1.0.3";
const char* PARSE_PUSH = "your-domain.com";  //"push.parse.com";
const unsigned short SSL_PORT = 443; // use 80 if you are using none of ssl (recommend ssl)

**Comment by robertochajin** [comment]
I already tweek my library, but it's not working....could you please provide an .ino example ???

thanks a lot

**Comment by Tom-Fox1** [comment]
I’m closing this as this project has been retired due to lack of use & contribution, if you wish to continue to use it please fork it or if you wish to maintain this project make yourself known
