### ISSUE TITLE
Please make a release to get the updated category displayed in the Arduino Library Manager

### ISSUE THREAD

**Issue by 00alis** [parse-community/Parse-SDK-Arduino#13]
Hi!
On https://create.arduino.cc/editor (the Arduino Web IDE) we include all the libraries in the Library Manager, your library is giving a warning for every single compilation, and many users have complained about it on our Forum.
WARNING: Category '' in library Parse Arduino SDK is not valid. Setting to 'Uncategorized'

This is due to the fact that you have modified the library.properties but haven't published a release yet.

We would really appreciate if you could make a release, so that the updated version will be automatically displayed in the Library Manager and the warning will disappear.

Thanks a lot!

**Comment by 00alis** [comment]
Hi, just pinging you on this issue. 
We have just 2 libraries giving problems on the Library Manager (out of more than 700) and we would really appreciate you make a release :)

Thanks again for your collaboration.

**Comment by Tom-Fox1** [comment]
Hi 👋 I'm sorry this has been overlooked for so long, I'm sure you have long since forgotten about this! I will try and look into making a new release within a few days.

**Comment by flovilmart** [comment]
@Tom-Fox1 you should probably archive this repo. Looks like no one needs / uses it. If people complain you can always transfer it.

**Comment by Tom-Fox1** [comment]
@flovilmart makes sense, I suppose it was never going to get much adoption beyond people tinkering with IoT.
