### ISSUE TITLE
error: 'ConnectionClient' does not name a type

### ISSUE THREAD

**Issue by kilabyte** [parse-community/Parse-SDK-Arduino#14]
Im getting this error after i have included the Parse.h header into my arduino sketch.
![screen shot 2017-02-27 at 5 03 37 pm](https://cloud.githubusercontent.com/assets/487948/23387001/b5e9a152-fd0e-11e6-80b5-27ab80009c28.png)

**Comment by AnChiChang** [comment]
same issue, anyone can help?

**Comment by Tom-Fox1** [comment]
I’m closing this as this project has been retired due to lack of use & contribution, if you wish to continue to use it please fork it or if you wish to maintain this project make yourself known
