### ISSUE TITLE
Connect to my own parse server

### ISSUE THREAD

**Issue by notiles** [parse-community/Parse-SDK-Arduino#8]
Hello,

Could you manage a modification to be able to connect my arduino to my own parse server?

Thanks a lot for that, it would save my life

**Comment by mtl2034** [comment]
@notiles, I will take a look at this issue this week.

**Comment by riccardoch** [comment]
As @notiles I'd like to connect my Arduino Yun to my own server and check push notifications.
Is it possible?

**Comment by adriamartines** [comment]
is it already resolved?

**Comment by notiles** [comment]
@riccardoch Sorry for the delay but I was in a work storm ;) Yes you can connect your yun to custom Parse server and send push notification or receive push in Arduino.

**Comment by riccardoch** [comment]
@notiles how can I do that? Thanks

**Comment by notiles** [comment]
Hello Riccardo,

First download the latest SDK/library here : https://github.com/ParsePlatform/Parse-SDK-Arduino

Edit the 2 first lines in the file in Examples/Arduino Yun/setup/Setup.ino

String revision = "1.0.5-1_ar71xx";
String location = "https://cdn.rawgit.com/ParsePlatform/parse-embedded-sdks/master/yun/linux_package/";

Save it in a new folder and launch this file. It will download and install the latest sdk on your Yun (1.0.5).

Then, open the file Examples/Arduino Yun/test/Test.ino, save it in a new folder and edit lines 120 and 121 with your credentials (clientID, key and parse server URL)

This file will run a test that create/delete/edit datas on you parse server.

If everything run correctly, you could go to the next step : receive Push notifications.

Open Examples/Arduino Yun/blink/Blink.ino you will find an example on how receive Push notifications. Now create a new file, setup it correctly with your credentials (like in the test.ino) and edit the loop to receive push notifications like in Blink.ino file. 

Now with your Parse dashboard you will be able to send push notifications to this board by passing the installation ID.

Let me know if you are facing issues, I will try to help.

**Comment by waqas-ogc** [comment]
@notiles Could you please help me connecting ESP8266 to my own parse server ?

**Comment by tabvn** [comment]
@waqas-ogc 



You need tweek a bit in this librarry

/src/internal/esp8266/parseClient.cpp

const bool DEBUG = false;
const char* PARSE_API = "your-domain.com"; //"api.parse.com";
const char* USER_AGENT = "arduino-esp8266.v.1.0.1";
const char* CLIENT_VERSION = "1.0.3";
const char* PARSE_PUSH = "your-domain.com"; //"push.parse.com";
const unsigned short SSL_PORT = 443; // use 80 if you are using none of ssl (recommend ssl)

**Comment by Cinezaster** [comment]
Having the same problem. 
I also tried direct REST calls to the parse server with the ESP but no luck. Something todo with the certificates and the fingerprint. I have a parse server with multiple apps running with letsEncrypt certificates. 
Has someone a working example with this library?
Even If I'm using the `WiFiClientSecure.h` I can't even connect to my server.
And Yes I changed the parseClient.cpp file.

**Comment by montymxb** [comment]
We'll be giving the Arduino SDK some TLC coming up soon. Priority will be on making sure the sdk can be setup to work with [parse-server](https://github.com/parse-community/parse-server) out of the box. We'll also be going over some of these issues and seeing what we can resolve 👍 .

**Comment by Tom-Fox1** [comment]
I’m closing this as this project has been retired due to lack of use & contribution, if you wish to continue to use it please fork it or if you wish to maintain this project make yourself known
